### ISSUE TITLE
[Dungeon] Maraudon - Lord Vyletongue Abilities

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#104]
**Description:**

Lord Vyletongue is missing the ability Putrid Breath (21601)
https://classicdb.ch/?npc=12236#abilities

**Current behaviour:**

All of his other abilities are fine but Putrid Breath is missing

**Expected behaviour:**

Putrid Breath should be used periodically

**Comment by Cillez** [comment]
Can confirm.

Fix:
```INSERT INTO `smart_scripts` VALUES
(12236, 0, 4, 0, 4, 0, 100, 0, 0, 0, 0, 0, 0, 11, 21080, 4, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Aggro - Cast Putrid Breath on self');```

**Comment by HelloKitty** [comment]
@whammyresilience , @Cillez made a PR to fix these things. Can you go check them and see if it's working? Going to merge to staging to get it deployed.

**Comment by whammyresilience** [comment]
The abilities are now being used. Interesting note: they miss on a level 60 character.
