### ISSUE TITLE
[Dungeon] Lower Blackrock Spire - Spirestone Lord Magus - Abilities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#110]
**Current behaviour:**

[Spirestone Lord Magus](https://classicdb.ch/?npc=9217#abilities) should have the following ability: [Enlarge](https://classicdb.ch/?spell=8365)

**Expected behaviour:**

Spirestone Lord Magus should cast this on a nearby melee mob if they exist. 

**Steps to reproduce the problem:**

1. Fight this NPC and another one that is melee and see that the ability is not cast.

**Comment by Nyeriah** [comment]
He's only casting it when under 50% health atm. Let me know if that's wrong

**Comment by whammyresilience** [comment]
I can't find anything specific, but logically this seems correct. Closing as resolved for the time being, as the ability is being used.
