### ISSUE TITLE
[Dungeon] Dire Maul: West - NPC Placement

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#12]
**Description:**

Ironbark the Redeemed is Standing in the courtyard for Dire Maul: West

**Current behaviour:**

See above

**Expected behaviour:**

He should be located in Dire Maul: East

**Steps to reproduce the problem:**

1. Enter Dire Maul: West
2. Run to the other side of the courtyard by the entrance to Tendris Warpwood's area

**Comment by HelloKitty** [comment]
Yea, this is confirmed. I think he's suppose to spawn in place of Old Iron Bark after you kill Zhermin or whatever the demons name is. DM:W will require some significant rescripting but I will get on that today.

**Comment by natnat201193** [comment]
https://github.com/KurthosWoW/TrinityCore/issues/143
