### ISSUE TITLE
[Dungeon] Dire Maul: North - Gordok Mastiff - Abilities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#127]
**Current behaviour:**

[Gordok Mastiff](https://vanilla-twinhead.twinstar.cz/?npc=13036#abilities) is not using the following ability: [Tendon Rip](https://vanilla-twinhead.twinstar.cz/?spell=3604)

**Expected behaviour:**

Gordok Mastiff should use this ability periodically on its target.

**Comment by Nyeriah** [comment]
It works fine for me, please check it again

**Comment by whammyresilience** [comment]
Resolved.
