### ISSUE TITLE
[Dungeon] Dire Maul: West - Ferra - Ablities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#166]
**Current behaviour:**

[Ferra ](https://vanilla-twinhead.twinstar.cz/?npc=14308#abilities)uses Maul.

**Expected behaviour:**

[Ferra ](https://vanilla-twinhead.twinstar.cz/?npc=14308#abilities)should use [Charge ](https://vanilla-twinhead.twinstar.cz/?spell=22911)on aggro and then use Maul and melee attacks. Charge does not currently happen at all. 

**Steps to reproduce the problem:**

1. Stand in at the edge of aggro range and wait for aggro.
2. Ferra just runs to you and starts attacking.

**Comment by Nyeriah** [comment]
Is it still not working after https://github.com/NoxGaming/TrinityCore/commit/3efacd0d83d9525400122e682a7c7b2475af36fb#diff-5cae95861188d3ede9f76d2c4a0e0a0a ?

**Comment by whammyresilience** [comment]
This is now working correctly.
