### ISSUE TITLE
[BWL] Blackwing Legionnaire - Abilities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#201]
**Current behaviour:**

[Blackwing Legionnaire](https://classicdb.ch/?npc=12416), a spawn during the Razorgore fight, only uses a melee attack.

**Expected behaviour:**

Blackwing Legionnaire should use the following abilities:

[Cleave](https://classicdb.ch/?spell=15284)
[Dragonbane](https://classicdb.ch/?spell=23967)
[Strike](https://classicdb.ch/?spell=15580)

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/db3924ae8075698605806008ce12cfd83a34e1cd
