### ISSUE TITLE
[BWL] Blackwing Mage - Abilities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#202]
**Current behaviour:**

[Blackwing Mage](https://classicdb.ch/?npc=12420), a spawn during the Razorgore fight, only uses a melee attack.

**Expected behaviour:**

Blackwing Mage should use the following abilities:

[Arcane Explosion](https://classicdb.ch/?spell=22271)
[Fireball](https://classicdb.ch/?spell=17290)

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/43ef18a9a8d244e8abae510c6ad0331d5e1aacad
