### ISSUE TITLE
[BWL] Blackwing Taskmaster - Abilities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#203]
**Current behaviour:**

[Blackwing Taskmaster](https://classicdb.ch/?npc=12458), a spawn during the Razorgore fight, only uses a melee attack.

**Expected behaviour:**

Blackwing Taskmaster should use the following abilities:

[Healing Circle](https://classicdb.ch/?spell=22458)
[Shadow Shock](https://classicdb.ch/?spell=17289)

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/4e0cf5b550621e87ffdbd95a91eaee49c8088e56
