### ISSUE TITLE
[BWL] Blackwing Guardsman - Abilities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#204]
**Current behaviour:**

[Blackwing Guardsman](https://classicdb.ch/?npc=14456), located next to Grethok the Controller, only melee attack.

**Expected behaviour:**

Blackwing Guardsman should use the following abilities:

[Cleave](https://classicdb.ch/?spell=15284)
[Dragonbane](https://classicdb.ch/?spell=23967)
[Strike](https://classicdb.ch/?spell=15580)

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/36f298f75e66f1d72a31a0f8876a22117db9090c
