### ISSUE TITLE
[BWL] Death Talon Dragonspawn - Abilities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#205]
**Current behaviour:**

[Death Talon Dragonspawn](http://classicdb.ch/?npc=12422#abilities), a spawn during the Razorgore fight, only uses a melee attack.

**Expected behaviour:**

Death Talon Dragonspawn should use the following abilities:

[Cleave](https://classicdb.ch/?spell=15284)
[Dragonbane](https://classicdb.ch/?spell=23967)
[Strike](https://classicdb.ch/?spell=15580)

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/50f404105ece716da66284545650c107ef971e62
