### ISSUE TITLE
[Warlock] Tier 3 6p set bonus - not working correctly

### ISSUE THREAD

**Issue by Glonz** [NoxGaming/TrinityCore#221]
**Description:**
The 6 set bonus of the warlock's Tier 3 Plagueheart raiment reduces the threat generated by critical spell hits by 25% and additionally, some warlock spells (Immolate, Corruption and Curse of Agony) generate 25% less threat.

**Current behaviour:**
The threat generated by Corruption, Immolate and Curse of Agony is reduced correctly, however, spell critical hits do not have reduced threat.

**Expected behaviour:**
In addition to the 25% threat reduction of Corruption, Immolate and Curse of Agony, spell critical hits made by the warlock should generate 25% less threat.

Itemset ID Plagueheart Raiment 529
Spell ID Plagueheart 28746

**Comment by Nyeriah** [comment]
https://github.com/NoxGaming/TrinityCore/commit/48cfaadf538900503d7bc06cd75211e74bc7354d

**Comment by Glonz** [comment]
Shadow Bolt r9 w/o T3 6p non crit 720 threat
Shadow Bolt r9 w/ T3 6p non-crit 742 threat

Shadow Bolt crit w/o T3 6p crit 60 threat
Shadow Bolt crit w/ T3 6p 832 threat

It appears that now any critical spell strikes deal almost no threat at all.

**Comment by Nyeriah** [comment]
I can see that, thanks
