### ISSUE TITLE
[DMW] Dire Maul Crystal Totem - should not be targetable

### ISSUE THREAD

**Issue by Glonz** [NoxGaming/TrinityCore#229]
**Description:**
In Dire Maul West, at the crystal pylon near the dungeon entrance, there is an invisible, yet targetable "Dire Maul Crystal Totem". It should not be targetable by players.

Creature ID 13916

**Comment by Nyeriah** [comment]
https://github.com/NoxGaming/TrinityCore/commit/519d5b5f9036e131d31b85894047bfef9e32094f
