### ISSUE TITLE
Dungeon: Dire Maul N Stun Mechanics.

### ISSUE THREAD

**Issue by HelloKitty** [NoxGaming/TrinityCore#37]
Several of the bosses have mechanics that can stun targets. I have not implemented these abilities because I am not sure if they should ignore the tank and only target melee, or if they only target the tank.

We'll need some data somewhere in the form of a video or something. Or, even a packet log. But I don't we can get or have that.

So, going to close #7 and #8 which should consolidate the remaining abilities that need to be implemented between them.

**Comment by HelloKitty** [comment]
Still need more information about this guys.

**Comment by whammyresilience** [comment]
#8

**Comment by whammyresilience** [comment]
Closing this due to #8 including this information since I reopened it.
