### ISSUE TITLE
[Dungeon] Stratholme - Ghostly Citizen Abilities

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#49]
**Description:**

Ghostly Citizen is missing ability Veil of Shadow (17820)
https://classicdb.ch/?npc=10385#abilities

**Current behaviour:**

Ghostly Citizens do not cast Veil of Shadow

**Expected behaviour:**

They should periodically cast Veil of Shadow while you are fighting them

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/e1e5b12275a48162703f43fd305177c39896c0e8
