### ISSUE TITLE
[Dungeon] Stratholme - Spectral Citizen Abilities

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#50]
**Description:**

Spectral Citizens are missing the abilities Debilitating Touch (16333) and Haunting Phantoms (16336)
https://classicdb.ch/?npc=10384#abilities

**Current behaviour:**

They cast neither of those abilities 

**Expected behaviour:**

Both spells should be cast when you fight them

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/a4c0fc1583e03497d58826acb209406fd29b5732

**Comment by Nyeriah** [comment]
https://github.com/NoxGaming/TrinityCore/commit/efcbf518add493259b4fcb23942bd1769cf448fa
