### ISSUE TITLE
[Class][Hunter] Volley does not cancel auto shot during use

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#53]
**Current behaviour:**

If you cast Volley your hunter will continue to auto shot the NPC you were single targeting before, assuming you were attacking it. 

**Expected behaviour:**

Once Volley is used, Auto Shot should pause until the end of Volley and then resume. 

**Steps to reproduce the problem:**

1. Start ranged attack on dummy.
2. Use Volley.
3. Observe Auto Shots while you channel Volley.

I'll add a screenshot later if needed.

**Comment by Nyeriah** [comment]
https://github.com/NoxGaming/TrinityCore/commit/7c81abd9f3e433de93ff5dbbeb6051cf3eac68b2
