### ISSUE TITLE
[Dungeon] Dire Maul: East - Warpwood Crusher Abilities

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#81]
**Description:**

Warpwood Crusher is missing the ability Trample (15550)
https://classicdb.ch/?npc=13021#abilities

**Current behaviour:**

Currently Warpwood Crushers only use Crush Armor

**Expected behaviour:**

They should be casting Trample while you fight them

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/69a9f852e6a5f9077fc4156950b4b4b6c83e77f0

**Comment by Glonz** [comment]
Still only casts Crush Armor.
