### ISSUE TITLE
[Dungeon] Dire Maul: East - Pimgib Movement

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#86]
**Description:**

Pimgib does not move into melee range, even after running out of mana

**Current behaviour:**

He stands there

**Expected behaviour:**

He should be meleeing in between spell casts

**Steps to reproduce the problem:**

1. Run to Pimgib in DM:E
2. Drain his mana

**Comment by natnat201193** [comment]
https://cdn.discordapp.com/attachments/486649827925688331/492252025384468499/Lethtendris_Pimgib_and_Hydrospawn.sql data from Vmangos, will look in to converting it for TC or moving it to CPP depending on whats needed.

**Comment by whammyresilience** [comment]
Closing due to duplicate with more information #211
