### ISSUE TITLE
[Dungeon] Dire Maul: East - Lethtendris Movement

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#87]
**Description:**

Lethtendris does not move into melee range, even after being drained to 0 mana

**Current behaviour:**

She stands there

**Expected behaviour:**

She should be meleeing in between casts

**Steps to reproduce the problem:**

1. Run to Lethtendris (right next to the previously reported Pimgib) 
2. Mana Drain Lethtendris

**Comment by whammyresilience** [comment]
Closing due to duplicate with more information #211
