### ISSUE TITLE
[Dungeon] Dire Maul: East - Hydrospawn Abilities

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#90]
**Description:**

Hydrospawn is missing the ability Massive Geyser (22421)
https://classicdb.ch/?npc=13280#abilities

**Current behaviour:**

The other abilites are working fine, but Massive Geyser is not cast

**Expected behaviour:**

Massive Geyser should be cast periodically

**Comment by natnat201193** [comment]
https://cdn.discordapp.com/attachments/486649827925688331/492252025384468499/Lethtendris_Pimgib_and_Hydrospawn.sql data from Vmangos, will look in to converting it for TC or moving it to CPP depending on whats needed.

**Comment by Nyeriah** [comment]
https://github.com/NoxGaming/TrinityCore/commit/fee680ae6d5f758c7100b963b35e83703e7d07dc
